### ISSUE TITLE
Visualizations persist after crawls have finished

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#737] opened 2015-10-28 14:52 UTC
New crawls created have the same graph as a crawl that has run previously. This may be related to #736 .

**Comment by ahmadia** [comment] 2015-10-28 14:54
This is an independent issue.  The visualizations all use the same routing key / queue for messages and the same Bokeh server document for storage.  The status updates are handled between Celery and Nutch, and should be resilient under multiple crawls.  I'll see if I can reproduce.

**Comment by ahmadia** [comment] 2015-10-28 15:46
Okay, I'm going to use a different Bokeh server document for each visualization.  This won't fix the fact that crawl viz. messages will go haywire if you run two simultaneous crawls, but it should also serially run subsequent crawls to behave more correctly, and we need this anyway.

**Comment by ahmadia** [comment] 2015-10-28 15:58
I had initially coupled the Bokeh document name to the queue name when it looked like we were configuring one queue/exchange per crawl.  Since we're using a routing key approach we need:

* routing key (*should be same as crawl name*)
* queue (can still be "fetcher_log" or maybe something more descriptive)
* Bokeh document id (*should be the same as crawl name*)

It's possible that we'll have to further restrict this based on restrictions in acceptable routing keys/document ids, but I'll try this approach for now.

**Comment by ahmadia** [comment] 2015-10-28 16:22
Okay, I've fixed this as well as I can for now.  In order to properly display any visualization on the second crawl we really need to get the routing working.

**Comment by ahmadia** [comment] 2015-10-28 16:23
https://github.com/memex-explorer/memex-explorer/commit/ec11c2c55d76b710334769299bedb9213f3c612e

**Closed** 2015-10-28 16:26 UTC

**Comment by ahmadia** [comment] 2015-10-29 15:56
amended to https://github.com/memex-explorer/memex-explorer/commit/1a718dfda6930b20302c8e34b86df5e30c05a469
